name: Test Automation Framework Workflow

on:
  schedule:
  - cron: 00 22 * * 1
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Downloading maven dependency
      run: mvn clean install -DskipTests

    - name: Running test Automation Framework with maven
      run: mvn test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false
      
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test logs
        path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Reports
        path: report.html

    - name: Test execution status
      run: echo "Test Execution Completed"

